language: python
python:
    - "3.6"
    - "3.7"

install:
    - pip install codecov
    - pip install -U pytest
    - pip install -U pytest-cov
    - python setup.py install

script:
    - pytest --cov=maup tests/

# Push the results back to codecov
after_success:
    - codecov
